---
namespace: hellqvio86
name: unifi
version: 0.0.19
readme: README.md
authors:
  - Olof Hellqvist (@hellqvio86)
description: Ansible collection for managing UniFi Network and UniFi OS.
license:
  - MIT
tags:
  - networking
  - security
  - infrastructure
repository: https://github.com/hellqvio86/ansible-collection-unifi
documentation: https://github.com/hellqvio86/ansible-collection-unifi
homepage: https://github.com/hellqvio86/ansible-collection-unifi
issues: https://github.com/hellqvio86/ansible-collection-unifi/issues
build_ignore:
  - ".github"
  - ".vscode"
  - "*.pyc"
  - "*.pyo"
  - ".antigravity*"
  - ".venv"
  - "tests"
  - "Makefile"
  - "pytest.out"
  - ".ruff_cache"
  - ".pytest_cache"
  - "releases"
  - "requirements.txt"
  - "pyproject.toml"
  - ".ansible"
  - "test_output.txt"
  - "agents.md"
